### ISSUE TITLE
Security: ``.env`` file shouldn't be in your GitHub repo 😬 

### ISSUE THREAD

**Issue by joe-dev-public** [fac24/week2-Minju-Hussain-Asmahan-George#30]
I see ``.env`` listed in your ``.gitignore`` file, but somehow it's ended up in your repo anyway. (And I think issue #26 already refers to this :)

(As you probably know, your ``.env`` contains your Heroku Postgres secret credentials. So anyone with access to this repo can directly access your database.)

Once something's been committed to your repo, it's quite hard to remove all records of it. So one quick fix is:
- Remove the ``.env`` file from your repo.
- Accept that those credentials are "compromised" (anyone could find them in the future by digging through your repo history).
- Delete the Heroku Postgres add-on with those credentials, and make a new one,
  - OR "rotate" (i.e. reset) the credentials. (The link below suggests that you do ``heroku pg:credentials:rotate`` from the Heroku CLI. I assume that this would have to be done by whoever actually made/owns the app on Heroku.)
- Everyone in the team make their own ``.env`` file in their local repo, with the new credentials (this is what our team did).
- Make sure this is actually in your local ``.gitignore`` so it can't ever be tracked/added/committed/pushed/merged!

More broadly:

The guidance isn't clear, but on this page Heroku talk about never copying the secret database URI anywhere: https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku (Our team didn't do this btw! Looked too complicated for this project.)

I assume one real-world best practice is to not use the same database server for deployment and development. (You'd still want to keep your dev server credentials away from your repo though :)

**Comment by minju25kim** [comment]
Thank you Joe for the steps how to do it!
